language: cpp

os:
  - linux
  - osx
dist: xenial
sudo: required
compiler:
  - clang
  - gcc

env:
  - QT=55 BREW=@5.5 PPA=ex
  - QT=56 BREW=@5.6 PPA=beineri/opt-qt563-xenial
  - QT=57 BREW=ex   PPA=beineri/opt-qt571-xenial
  - QT=59 BREW=ex   PPA=beineri/opt-qt597-xenial
  - QT=510 BREW=@5.10 PPA=beineri/opt-qt-5.10.1-xenial
  - QT=511 BREW=@5.11 PPA=beineri/opt-qt-5.11.2-xenial

matrix:
  exclude:
    - { os: linux, compiler: clang }
    - { os: osx, compiler: gcc }
    - { os: linux, env: QT=55 BREW=@5.5 PPA=ex }
    - { os: osx, env: QT=57 BREW=ex   PPA=beineri/opt-qt571-xenial }
    - { os: osx, env: QT=59 BREW=ex   PPA=beineri/opt-qt597-xenial }

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt${QT}base qt${QT}script'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - qmake -v

script:
  - qmake "CONFIG+=debug" QtBkBtl.pro
  - make
